Update to SF 8.2 CU1
darinegan/chocolatey-packages pull request #14
Opened 2021-12-21 14:20 UTC by nicolas-garcia

Hello,

Update to SF 8.2 CU1

https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_82CU1.md

Thank you @darinegan !

2022-01-04 14:03 UTC, darinegan commented
Hi @nicolas-garcia 

Apologies for my delay; I've just returned from leave over the holidays. Firstly, thank you for your contribution and taking the time to share. I've reviewed the PR and have 1 item for your attention.

2022-01-04 14:04 UTC, darinegan requested changes

2022-01-04 14:04 UTC, darinegan commented on automatic/service-fabric-sdk/service-fabric-sdk.nuspec
> +    <version>5.2.1363</version>
Can you confirm whether this change in SDK version to 1363 has any dependency on the related "service-fabric" package version 1363 or can remain at 1235?

```xml
<dependencies>
    <dependency id="service-fabric" version="8.2.1235" />
</dependencies>
```

2022-01-11 15:34 UTC, nicolas-garcia commented on automatic/service-fabric-sdk/service-fabric-sdk.nuspec
> +    <version>5.2.1363</version>
Hi @darinegan

Sorry for the delay, I was on holiday too :)
I think I missed this dependency at first. Good catch, thank you!

2022-01-14 10:47 UTC, darinegan approved these changes

2022-01-14 10:47 UTC, merged

2022-01-14 11:32 UTC, darinegan commented
Thanks @nicolas-garcia for your work on this. I've approved and merged this PR. I also pushed this version to Chocolatey.org which is pending review.