Update to service fabric 9.1.1390
darinegan/chocolatey-packages pull request #19
Opened 2022-11-09 21:30 UTC by mjsabin01

# Description

Update to Service Fabric 9.1.1390 packages

2022-11-11 10:48 UTC, darinegan requested changes
Michael, thank you for taking the time to contribute this PR.

I need to return to correct the "smimesign" package which is failing to update correctly. Can you remove any changes to "smimesign" package as part of this PR?

2022-11-11 14:48 UTC, mjsabin01 commented
Hello. I pushed a change to remove the change to smimesign.

2022-11-14 09:44 UTC, darinegan approved these changes

2022-11-14 09:45 UTC, merged

2022-11-14 09:52 UTC, darinegan commented
Thanks Michael, this is merged and pushed to Chocolatey pending review. Should be available within 24-48 hours.